### ISSUE TITLE
Filter log command based on user's category preference

### ISSUE THREAD

**Issue by taladar** [iridakos/stup#12]
It always displays all categories when I use e.g.

```
stup log -c work
```

**Comment by iridakos** [comment]
Yes, it doesn't support category filtering but it's a nice feature.

I will mark this issue as improvement and I will keep it open to be implemented.

Thanks for your feedback!

**Comment by taladar** [comment]
If it doesn't support that the --help option probably shouldn't list it though

```
stup log --help
```

shows

```
 -c, --category   Specifies the category whose notes will be listed.
                  If omitted, stup will list the notes of all categories.
                  Example: stup log -c work week
```

**Comment by iridakos** [comment]
You are right! I checked the README file only which doesn't have this option. I'll update the usage information as well.

Thank very much!

**Comment by iridakos** [comment]
@taladar Done :+1:
