### ISSUE TITLE
Errors in README

### ISSUE THREAD

**Issue by tiosgz** [iridakos/stup#13]
Hi,
I found a few errors in the README:
* [Show today's notes](https://github.com/iridakos/stup#show-todays-notes) has the same code as show yesterday's notes
* description of [edit notes](https://github.com/iridakos/stup#edit-notes) contains `<note-text>`
* [list categories](https://github.com/iridakos/stup#list-your-categories) has `order-categories` in summary
* [contributing](https://github.com/iridakos/stup#contributing) — fork the *repository*, not *category*? :-P
* maybe the same for [future work](https://github.com/iridakos/stup#future-work)

**Comment by iridakos** [comment]
Hi @tiosgz,

Thank you very much for reporting them!
I will update the file asap.

:+1:

**Comment by iridakos** [comment]
@tiosgz Done :+1: 

**Fun fact:** when I started implementing `stup`, I used the term `repository` for what today is `category`. When I decided that `category` is a more suitable term, I mass replaced :unamused: its occurrences in README and that's the reason of the errors in the "Contributing" and "Future work" sections :D
