### ISSUE TITLE
zsh

### ISSUE THREAD

**Issue by iridakos** [iridakos/stup#14]
The tool should be able to be executed in `zsh`

**Comment by tiosgz** [comment]
For me it works well in `zsh` (Manjaro Linux, `zsh` 5.8). Maybe there were some problems with the tools being different on McOS, or with the particular user setup?

**Comment by iridakos** [comment]
That's very good news.

I don't use `zsh` and I thought it would have issues because in one of my [other scripts](https://github.com/iridakos/goto) I had to change some stuff to make it work. Most of them though I think that were about the tab completion feature.

Closing the issue, thank you!
