### ISSUE TITLE
Add options for defaults

### ISSUE THREAD

**Issue by tiosgz** [iridakos/stup#21]
I use `add` more than `show` and `show today` much more than `show yesterday`. The configuration file should contain some settings for this.

**Comment by tiosgz** [comment]
See #22, but I think all defaults should have their settings.

**Comment by iridakos** [comment]
Great!

**Comment by iridakos** [comment]
@all-contributors please add @tiosgz for ideas

**Comment by iridakos** [comment]
Merged! :pray:
