### ISSUE TITLE
Feature Request: Ability to copy notes of a category from one date to another

### ISSUE THREAD

**Issue by ioanniswd** [iridakos/stup#34]
For tasks that span multiple days, it would be handy to be able to copy yesterday's notes to today's notes.

**Comment by ioanniswd** [comment]
Does a new `copy` command sound better that updating the functionality of the existing `add` command? 

This is what I have in mind:

`stup <copy|add> @|--at|-@ <when> -n|--note "<note text>" -c|--category "<category-name> --from <copy-from-date> --from-category <copy-from-category-name>"`

With <when> and <category-name> behaving in the exact same way as in the `add` command, and:
 * `<copy-from-date>`: specifies the date from which the notes will be copied
   * any of the words: `today`, `tomorrow`, `yesterday`
   * a date string in the form: `YYYY-MM-DD`, for example: 2020-04-12
   * if you omit this option, stup by default will copy the notes from `yesterday`
 * `--from-category`: is the category option from which to copy (optional). **If omitted, notes will be copied from your default category**


Also, a prompt for each note to be copied might be nice with the options `y(es)/n(o)/a(ll)/q(uit)`

How does that sound?

**Comment by tiosgz** [comment]
> * `--from-category`: is the category option from which to copy (optional). **If omitted, notes will be copied from your default category**

Wouldn't copying from the same category (by default) be better? I think that usually when you want a note (or more) for several days, you want it (them) still in the same category, and not to travel…
> Also, a prompt for each note to be copied might be nice with the options `y(es)/n(o)/a(ll)/q(uit)`

I'm quite curious how this could be done simply with multi-line notes (yes I use them a lot)… (OK, some more `y<Enter>` or `n<Enter` wouldn't be so difficult)

I also thought that a "sticky" category (or whatever) could be made, but then I let it be coz it's not good for me… And I don't think it would be worth the effort put in it.

**Comment by ioanniswd** [comment]
> Wouldn't copying from the same category (by default) be better? I think that usually when you want a note (or more) for several days, you want it (them) still in the same category, and not to travel…

Yes, that is the case for me too.

> I'm quite curious how this could be done simply with multi-line notes (yes I use them a lot)… (OK, some more y<Enter> or n<Enter wouldn't be so difficult)

I am thinking that if we can distinguish multi-line notes with the `show` command, we could do the same for the `copy` command prompt.

**Comment by ioanniswd** [comment]
Seeing how `--copy-from-date` might be too long an option name to use with a custom date from which to copy, I am thinking of creating `from_yesterday`, `from_today`, `from_tomorrow`  options instead. Also starting to lean towards creating a new `copy` command instead of altering the existing `add` command.

**Comment by iridakos** [comment]
Yes, I agree. `copy` should be implemented as a new action.

> Seeing how --copy-from-date might be too long an option name to use with a custom date from which to copy, I am thinking of creating from_yesterday, from_today, from_tomorrow options instead

I think we can keep the `--from` and `--to` flags (already known to users).

## Examples
```bash
# Implying copy to today
stup copy --from yesterday -c meetings

# Explicit destination date
stup copy --from 2020-04-30 --to today --c "pr-reviews"
```

**Comment by ioanniswd** [comment]
> I think we can keep the --from and --to flags (already known to users).

Thinking I should I then remove the implicit invocation of `log` in case command is not present and `from`/`to` are present.

**Comment by iridakos** [comment]
Are you thinking about changing the command `log` to `copy` in this case or just removing the implication? I think it should default to `log` action that doesn't alter the notes and let `copy` action to be explicitly set as an argument. What say you?
