### ISSUE TITLE
Add configuration for which pager to use

### ISSUE THREAD

**Issue by haganbmj** [iridakos/stup#41]
Currently the pager is using `more`. I don't have `more` set up to use repaint (`-R`) by default, so the output is without resolved color codes. I'd like to be able to configure the command used, in the event that I want to add the flag, use `less`, or use some other equivalent.

example output without `-R` for reference.

![Screen Shot 2020-05-06 at 18 31 39](https://user-images.githubusercontent.com/15820761/81234993-ed41d580-8fc7-11ea-901c-c3c587af036a.png)

**Comment by iridakos** [comment]
:+1:

**Comment by tiosgz** [comment]
You caused me to pipe it to `lolcat` while testing… We need to use the pager more… We need to use the pager more… :-P

**Comment by iridakos** [comment]
@all-contributors please add @haganbmj for ideas

**Comment by iridakos** [comment]
@all-contributors please add @haganbmj for ideas
