### ISSUE TITLE
stup week misbehave

### ISSUE THREAD

**Issue by EnergoKoder** [iridakos/stup#52]
I type commands like this:

```bash
date > stup-week.txt
stup week >> stup-week.txt
cat ./stup-week.txt
```

And the output is like this:

```
pon, 9 lis 2020, 16:29:04 CET
[38;5;248mDisplaying notes from(B[m [32mponiedziałek listopada 02, 2020(B[m [38;5;248mto(B[m [32mniedziela listopada 08, 2020(B[m

Date:      [1m[32mponiedziałek listopada 02, 2020(B[m(B[m
Category:  [33mplany(B[m

           • Nauka matematyki.

Date:      [1m[32mwtorek listopada 03, 2020(B[m(B[m
Category:  [33mplany(B[m

           • Nauka matematyki.
           • Kopia zapasoawa.
           • Certyfikat BHP do biblioteki.
           • Instrukcja laborki z fizyki.

Date:      [1m[32mśroda listopada 04, 2020(B[m(B[m
Category:  [33mdziałania(B[m

           • 17:46:27 Jedzenie pizzy Gusepe.
           • 18:29:10 Nauka matematyki.
           • 20:17:34 Nauka fizyki.

Category:  [33mplany(B[m

           • Nauka matematyki: 18:00-20:00.
           • Nauka fizyki: 20:00-21:15.

Date:      [1m[32mczwartek listopada 05, 2020(B[m(B[m
Category:  [33mdziałania(B[m

           • 17:45:00 Nauka fizyki.
           • 19:00:01 Mycie szklanego stołu. Porządkowanie dokumentów samochodu. Zamawianie koszulek na materiały do nauki.
           • 20:21:00 Aktualizacja Podstawowe Zabezpieczenie Stacji Roboczych Linux Debian.

Category:  [33mplany(B[m

           • 17:00 Konsultacje.
           • 17:30-19:00 Nauka fizyki.
           • 19:20-21:20 Aktualizacja Podstawowe Zabezpieczenie Stacji Roboczych Linux Debian.

Date:      [1m[32mniedziela listopada 08, 2020(B[m(B[m
Category:  [33mplany(B[m

           • Lab. z fizyki: ćw. Torsje.

```

Explanation:
Today is 2020-11-09. But `stup week` shows notes from 2020-11-02 to 2020-11-08. It is had to say if this is first week or previous week (but definitlely both). For seek of completnes I quote help:
```             week   Alias to list the notes of current week```

**Comment by tiosgz** [comment]
Since I don't hope for new PRs to be merged (@iridakos feel free to prove me wrong), I'll just give you what I think should fix it:

change
https://github.com/iridakos/stup/blob/187c8409ea10785bceb3ec87b38558abaea71755/stup#L1165
to
```bash
      FROM_AT=$(date -d "$(($(date +%u) - 1)) days ago" +"%Y-%m-%d")
```

Please let me know if it works as you want, when I get time&mood I'll re-check all such things & PR them (even if it won't be merged)

**Comment by iridakos** [comment]
@EnergoKoder Thank you for reporting this issue! @tiosgz Thank you for the workaround! And sorry for the delay merging this [PR](https://github.com/iridakos/stup/pull/51), I had forgotten it!

**Comment by tiosgz** [comment]
@iridakos Okay then, time to start working on the rest!

I've switched my notes system several times since then, but I think I'll enjoy `stup` once again. Btw., have you realised it's `puts` backwards? :-D

**Comment by iridakos** [comment]
> @iridakos Okay then, time to start working on the rest!

Yay! I will put some work on it as well, starting from a new configuration option that will allow users to set the list icon (currently set to a bullet).

> Btw., have you realised it's puts backwards? :-D

No I hadn't! :laughing:

**Comment by EnergoKoder** [comment]
> ```shell
> FROM_AT=$(date -d "$(($(date +%u) - 1)) days ago" +"%Y-%m-%d")
> ```

**Comment by EnergoKoder** [comment]
> Please let me know if it works as you want, when I get time&mood I'll re-check all such things & PR them (even if it won't be merged)

Works perfect! Thank you for rapid resurrection!
