### ISSUE TITLE
Fix pager

### ISSUE THREAD

**Issue by ghost** [iridakos/stup#56]
I must’ve broken some of the options while playing with the pager. I haven’t investigated yet, I’ll do that before&while fixing it.

Of course you can assign me. Since I seem to be the only one having noticed this, I first want to finish what I started today though.

**Comment by iridakos** [comment]
@tiosgz Cool, thanks! :+1:

**Comment by ghost** [comment]
Now that I have tested it more, it seems to work again; sorry for the confusion. Maybe I tried to use it on `show` before.

```shell
$ export PAGER='sed -e s/^/got:/g'
$ # pager is 'false' in the config
$ stup log
Displaying all notes

Date:      Tuesday April 21, 2020
[...]
$ stup log --pager 'sed -e s/^/got:/g' --no-pager
Displaying all notes

Date:      Tuesday April 21, 2020
[...]
$ stup log --pager false
Displaying all notes

Date:      Tuesday April 21, 2020
[...]
$ # note that $PAGER is the sed expression
$ stup log --pager ''
Displaying all notes
got:
got:Date:      Tuesday April 21, 2020
[...]
$ stup log --pager 'sed -e s/^/got:/g' --pager false
Displaying all notes

Date:      Tuesday April 21, 2020
[...]
$ # set it to the sed expression in the config
$ vim ~/.config/stup.conf
$ stup log
Displaying all notes
got:
got:Date:      Tuesday April 21, 2020
[...]
$
```

While at the topic of pager, I have two questions:
* wouldn't it be better to pipe there everything except for fixed-length output (about to edit..., displaying...) & something that expects user interaction (`stup configure`, do you want to...)?
* what if it spawned another bash instance with the command?
    * this way, one could use arguments that contain spaces & also full bash syntax
    * however, it spawns another mostly useless process & differs from the standard way (i.e. could cause issues)
